@url = https://localhost:5053/orders

### Get orders
GET {{url}}?pageIndex=0&pageSize=10

### Create order
POST {{url}}
Content-Type: application/json

{
    "order": {
        "customerId": "58c49479-ec65-4de2-86e7-033c546291aa",
        "orderName": "ORD_4",
        "shippingAddress" : {
            "firstName": "ship fn",
            "lastName": "ship ln",
            "emailAddress" : "ship@email.com",
            "addressLine": "ship address",
            "country": "ship country",
            "state": "ship state",
            "zipCode": "41248"
        },
        "billingAddress" : {
            "firstName": "bill fn",
            "lastName": "bill ln",
            "emailAddress" : "bill@email.com",
            "addressLine": "bill address",
            "country": "bill country",
            "state": "bill state",
            "zipCode": "41248"
        },
        "payment": {
            "cardName": "CARD_1",
            "cardNumber": "875-444-3739",
            "expiration": "12/29",
            "cvv": "123",
            "paymentMethod": 1
        },
        "orderItems": [
            {
                "productId": "5334c996-8457-4cf0-815c-ed2b77c4ff61",
                "quantity": 2,
                "price": 500
            },
            {
                "productId": "c67d6323-e8b1-4bdf-9a75-b0d0d2e7e914",
                "quantity": 1,
                "price": 100
            }
        ]
    }
}

### Remove Order
DELETE {{url}}/85caa855-ad34-48be-ad9a-6fcb464adf2d