@url = https://localhost:5050/products
@id = 01903ecd-b031-4b62-b9da-cc3b93ae00c7

### Create a new product
PUT {{url}}/{{id}}
Content-Type: application/json

{
    "name": "P",
    "categories" : ["c1", "c2", "c0"],
    "description": "Product 1 description",
    "imageFile": "product1.jpg",
    "price": 2
}